# Generated by Django 3.0.5 on 2020-08-02 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import project.agency.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', project.agency.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aranzman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30, unique=True)),
                ('cena', models.IntegerField(default=0)),
                ('broj_dostupnih', models.IntegerField(default=10, verbose_name='broj dostupnih smeštajnih jedinica')),
                ('broj_rezervacija', models.IntegerField(default=0, verbose_name='broj rezervacija')),
                ('datum_polaska', models.DateField(verbose_name='datum polaska')),
                ('datum_dolaska', models.DateField(verbose_name='datum dolaska')),
            ],
            options={
                'verbose_name_plural': 'Aranžmani',
                'db_table': 'aranzman',
            },
        ),
        migrations.CreateModel(
            name='Destinacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drzava', models.CharField(max_length=30)),
                ('mesto', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Destinacije',
                'db_table': 'destinacija',
            },
        ),
        migrations.CreateModel(
            name='Prevoz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_prevoza', models.CharField(max_length=30, unique=True, verbose_name='vrsta prevoza')),
            ],
            options={
                'verbose_name_plural': 'Vrste prevoza',
                'db_table': 'prevoz',
            },
        ),
        migrations.CreateModel(
            name='Smestaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=500)),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Destinacija')),
            ],
            options={
                'verbose_name_plural': 'Smeštaji',
                'db_table': 'smestaj',
            },
        ),
        migrations.CreateModel(
            name='VrstaSmestaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_smestaja', models.CharField(max_length=30, unique=True, verbose_name='vrsta smeštaja')),
                ('broj_osoba', models.IntegerField(default=0, verbose_name='predviđen broj osoba')),
            ],
            options={
                'verbose_name_plural': 'Vrste smeštaja',
                'db_table': 'vrsta_smestaja',
            },
        ),
        migrations.CreateModel(
            name='TipSmestaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smestaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Smestaj')),
                ('vrsta_smestaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.VrstaSmestaja')),
            ],
            options={
                'verbose_name_plural': 'Tipovi smeštaja',
                'db_table': 'tip_smestaja',
            },
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to=project.agency.models.upload_path)),
                ('smestaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Smestaj')),
            ],
            options={
                'verbose_name_plural': 'Slike',
                'db_table': 'slika',
            },
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukupan_iznos', models.FloatField(default=0.0, verbose_name='ukupan iznos')),
                ('placeno', models.BooleanField(blank='false', verbose_name='plaćeno')),
                ('aranzman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Aranzman', verbose_name='aranžman')),
                ('prevoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Prevoz', verbose_name='prevoz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
            ],
            options={
                'verbose_name_plural': 'Rezervacije',
                'db_table': 'rezervacija',
            },
        ),
        migrations.AddField(
            model_name='aranzman',
            name='tip_smestaja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.TipSmestaja', verbose_name='tip smeštaja'),
        ),
    ]
