# Generated by Django 3.0.5 on 2020-08-03 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='datum_rezervacije',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='datum rezervacije'),
        ),
    ]
