# Generated by Django 3.0.5 on 2020-08-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_rezervacija_datum_rezervacije'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aranzman',
            name='broj_dostupnih',
        ),
        migrations.RemoveField(
            model_name='aranzman',
            name='naziv',
        ),
        migrations.AddField(
            model_name='tipsmestaja',
            name='broj_dostupnih',
            field=models.IntegerField(default=10, verbose_name='broj dostupnih smeštajnih jedinica'),
        ),
    ]
