# Generated by Django 3.0.5 on 2020-08-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20200803_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aranzman',
            name='datum_polaska',
            field=models.DateField(blank=True, null=True, verbose_name='datum polaska'),
        ),
    ]
