# Generated by Django 3.0.5 on 2020-08-06 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20200805_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='datum_rezervacije',
            field=models.DateField(default=datetime.date.today, verbose_name='datum rezervacije'),
        ),
        migrations.AlterField(
            model_name='tipsmestaja',
            name='smestaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Smestaj'),
        ),
    ]
