# Generated by Django 3.0.5 on 2020-08-15 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20200806_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aranzman',
            name='broj_rezervacija',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='broj rezervacija'),
        ),
        migrations.AlterField(
            model_name='aranzman',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aranzman',
            name='tip_smestaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.TipSmestaja', verbose_name='tip smeštaja'),
        ),
        migrations.AlterField(
            model_name='destinacija',
            name='drzava',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='destinacija',
            name='mesto',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prevoz',
            name='vrsta_prevoza',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='vrsta prevoza'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='aranzman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Aranzman', verbose_name='aranžman'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='datum_rezervacije',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='datum rezervacije'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='placeno',
            field=models.BooleanField(blank=True, null=True, verbose_name='plaćeno'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='prevoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Prevoz', verbose_name='prevoz'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='ukupan_iznos',
            field=models.FloatField(blank=True, null=True, verbose_name='ukupan iznos'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='korisnik'),
        ),
        migrations.AlterField(
            model_name='slika',
            name='smestaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Smestaj'),
        ),
        migrations.AlterField(
            model_name='smestaj',
            name='destinacija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Destinacija'),
        ),
        migrations.AlterField(
            model_name='smestaj',
            name='naziv',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='smestaj',
            name='opis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipsmestaja',
            name='broj_dostupnih',
            field=models.IntegerField(blank=True, null=True, verbose_name='broj dostupnih smeštajnih jedinica'),
        ),
        migrations.AlterField(
            model_name='tipsmestaja',
            name='smestaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Smestaj'),
        ),
        migrations.AlterField(
            model_name='tipsmestaja',
            name='vrsta_smestaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.VrstaSmestaja'),
        ),
        migrations.AlterField(
            model_name='vrstasmestaja',
            name='broj_osoba',
            field=models.IntegerField(blank=True, null=True, verbose_name='predviđen broj osoba'),
        ),
        migrations.AlterField(
            model_name='vrstasmestaja',
            name='vrsta_smestaja',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='vrsta smeštaja'),
        ),
    ]
